### ISSUE TITLE
question about API

### ISSUE THREAD

**Issue by cwiese** [JuliaWeb/Mux.jl#22]
I thought I knew a bit of Julia, but I am still a newbie.  I am trying to see how you would define a route that only match POST (and a different function for GET/OPTION).   "p" is the path ... I do not see anywhere the METHOD is considered in matching.

route(p, app...) = branch(req -> matchpath!(p, req), app...)
route(p::AbstractString, app...) = route(splitpath(p), app...)
route(app::Function, p) = route(p, app)

Also, if I use @app  ....and I have a few lines for each route ....this function get huge! 

@app app = (
    Mux.defaults,
    #page("/about",   req -> hello(req)),
    #method("GET",
    #route("Hello world!", "/about"),
    route(get_meta,"/api/p3meta"),
    Mux.notfound()
)

can I add after defining app?

**Comment by one-more-minute** [comment]
You can split by method by using the `GET` function [here](https://github.com/JuliaWeb/Mux.jl/blob/c1476b200b90b694a82fa28c6c1b863c7a51e0cd/src/routing.jl#L10), or alternatively `method("GET", ....)`, `method("PUT", ...)` etc. Extra functions like `PUT(...)` could be useful, so feel free to send a PR with those attached if you want ;)

You can't modify the route after defining the app as such, but you can build up the app gradually in order to cut the size down a bit. For example, you might pull out the about page from the readme example like this:

```julia
aboutpage = page("/about",
       probabilty(0.1, respond("<h1>Boo!</h1>")),
       respond("<h1>About Me</h1>"))

@app test = (
  Mux.defaults,
  page(respond("<h1>Hello World!</h1>")),
  aboutpage,
  page("/user/:user", req -> "<h1>Hello, $(req[:params][:user])!</h1>"),
  Mux.notfound())
```

Hope that helps, let me know if you have other questions!

**Comment by jpsamaroo** [comment]
@cwiese if Mike's response has answered your question, it would be best to close this issue, and if necessary, begin a discussion on Discourse or Slack instead. Alternatively, if there is still missing functionality that you require, can you update this issue's title to be more descriptive so that contributors have a clearer understanding of what feature is missing?
