### ISSUE TITLE
Problems with adding Mux on Julia 1.0.1

### ISSUE THREAD

**Issue by chlech** [JuliaWeb/Mux.jl#75]
Hi everyone,

I am new to julia and experience problems using Julia Pro 1.0.1 installation on Windows 10.
I get the following Error:

ERROR: Unsatisfiable requirements detected for package WebSockets [104b5d7c]:
 WebSockets [104b5d7c] log:
 ├─possible versions are: [0.0.1-0.0.6, 0.1.0-0.1.2, 0.2.0-0.2.3, 0.3.0, 0.4.0, 0.5.0, 1.0.0-1.0.3]
or uninstalled
 ├─restricted by julia compatibility requirements to versions: 1.0.0-1.0.3 or uninstalled
 ├─restricted by compatibility requirements with Mux [a975b10e] to versions: [0.0.1-0.0.6, 0.1.0-0.1
.2, 0.2.0-0.2.3, 0.3.0, 0.4.0, 0.5.0, 1.0.0-1.0.3], leaving only versions: 1.0.0-1.0.3
 │ └─Mux [a975b10e] log:
 │   ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.3, 0.3.0-0.3.1, 0.4.0, 0.5.0-0.5.3] or uninsta
lled
 │   ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.1, 0.2.
0-0.2.3, 0.3.0-0.3.1, 0.4.0, 0.5.0-0.5.3]
 │   └─restricted by julia compatibility requirements to versions: [0.3.1, 0.4.0, 0.5.0-0.5.3] or un
installed, leaving only versions: [0.3.1, 0.4.0, 0.5.0-0.5.3]
 └─restricted by compatibility requirements with HTTP [cd3eb016] to versions: [0.0.1-0.0.6, 0.1.0-0.
1.2, 0.2.0-0.2.3, 0.3.0, 0.4.0, 0.5.0] or uninstalled — no versions left
   └─HTTP [cd3eb016] log:
     ├─possible versions are: 0.7.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.7.0

_________________________________________________________________________________________________________

Is that an known issue or can anyone help?

Thank you!

**Comment by rdeits** [comment]
I believe this is because WebSockets.jl requires a very specific older version of HTTP.jl, and for some reason JuliaPro does not want to install that version. The root problem should be solved by this pull request: https://github.com/JuliaWeb/WebSockets.jl/pull/120

Can you perhaps try installing that version of HTTP? That would mean doing: 

```julia
 pkg> add HTTP@v0.6.14
```

**Comment by hustf** [comment]
Thanks to cheleh for letting us know so specifically about the difficulty.
I was under the impression everything worked fine just now.

Robin is spot on. We're working  (unfortunately for you, slowly)  with
adapting WebSockets to the latest released version of HTTP, release 0.7.0
to 0.7.99. Although seeing the requirements above, we should perhaps also
test specifically for HTTP version 0.7.0 in order to support JuliaPro.

The referred pull request tries to adapt to the, probably next in line,
experimental HTTP release. The work on released version is in this branch
https://github.com/JuliaWeb/WebSockets.jl/tree/http0.7.0
